language: ruby
rvm:
  - "2.4.1"
addons:
  chrome: beta
before_install:
  "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
